name: Build and Release

on:
  push:
    tags:
      - '**'

jobs:
  Build_and_Release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: microsoft/setup-msbuild@v1

      - run: MSBuild.exe $Env:GITHUB_WORKSPACE/UnityFinder/UnityFinder.csproj -p:Configuration=Release
        timeout-minutes: 5

      - uses: softprops/action-gh-release@v0.1.5
        with:
          draft: false
          prerelease: false
          files: UnityFinder/bin/Release/UnityFinder.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
